// ─── Aureva Training System — Complete Recipe Database (23 Recipes) ────────────

export const RECIPES = [
  // ── BREAKFAST ──────────────────────────────────────────────────────────────
  {
    id:1, num:'RECIPE 1', category:'breakfast', img:'/r1.jpg',
    name:'PROTEIN BREAKFAST BOWL',
    tag:'High protein. Clean fuel. Perfect start.',
    cal:420, protein:30, carbs:38, fat:12, fiber:6, sugar:12,
    perfectFor:['Busy mornings','Pre-workout fuel','Post-workout recovery','Weight loss','Muscle building'],
    ingredients:[
      '1 cup (170g) non-fat Greek yogurt',
      '1 scoop vanilla protein powder',
      '½ cup (40g) rolled oats',
      '½ cup mixed berries',
      '½ banana, sliced',
      '1 tbsp natural peanut butter',
      '1 tsp chia seeds',
      '1 tsp honey (optional)',
    ],
    steps:[
      'Add Greek yogurt to a bowl.',
      'Mix in protein powder until smooth.',
      'Top with oats, berries, banana, and chia seeds.',
      'Add peanut butter and a drizzle of honey.',
      'Enjoy immediately and fuel your day the Aureva way!',
    ],
    proTip:'Prep your oats the night before for an even faster morning!',
    swaps:['Use almond milk instead of yogurt for a lighter option','Swap peanut butter for almond butter','Use cottage cheese instead of yogurt for more protein'],
    goals:{
      fatLoss:{ changes:['Use non-fat Greek yogurt','Skip the honey','Keep peanut butter to 1 tsp'], cal:350, protein:32 },
      recomp: { changes:['Follow the recipe as is','Great for muscle retention'], cal:420, protein:30 },
      muscle: { changes:['Add 1 tbsp more peanut butter','Add ¼ cup granola','Add an extra ½ scoop protein'], cal:550, protein:40 },
    },
  },
  {
    id:2, num:'RECIPE 2', category:'breakfast', img:'/r2.jpg',
    name:'EGG WHITE SCRAMBLE',
    tag:'Light, protein-packed, and delicious.',
    cal:310, protein:35, carbs:10, fat:10, fiber:3, sugar:4,
    perfectFor:['Breakfast','Pre-workout meal','Weight loss','Muscle building','Busy mornings'],
    ingredients:[
      '1 cup (240ml) liquid egg whites (about 6–7 egg whites)',
      '¼ cup red bell pepper, diced',
      '¼ cup spinach, chopped',
      '¼ cup red onion, diced',
      '¼ cup mushrooms, sliced',
      '1 tbsp olive oil or cooking spray',
      'Salt & black pepper to taste',
      '¼ tsp garlic powder (optional)',
      '¼ tsp Italian seasoning (optional)',
    ],
    steps:[
      'Heat olive oil in a non-stick pan over medium heat.',
      'Add onions, peppers, mushrooms and cook for 3–4 minutes.',
      'Add spinach and cook until wilted.',
      'Pour in egg whites and stir gently.',
      'Cook for 3–4 minutes, stirring until eggs are set.',
      'Season to taste and enjoy!',
    ],
    proTip:'Add hot sauce or salsa for extra flavor without extra calories!',
    swaps:['Add turkey bacon or chicken for more protein','Swap veggies based on what you have','Use egg whole + whites for extra creaminess','Add avocado on the side for healthy fats'],
    goals:{
      fatLoss:{ changes:['Use cooking spray','Add more veggies'], cal:260, protein:32 },
      recomp: { changes:['Add a side of fruit or oats for extra carbs'], cal:350, protein:35 },
      muscle: { changes:['Add healthy fats and complex carbs','Add avocado + whole grain toast'], cal:450, protein:40 },
    },
  },
  {
    id:3, num:'RECIPE 3', category:'breakfast', img:'/r3.jpg',
    name:'GREEK YOGURT POWER BOWL',
    tag:'Simple. Nutritious. Absolutely delicious.',
    cal:360, protein:25, carbs:38, fat:10, fiber:6, sugar:18,
    perfectFor:['Breakfast','Post-workout','Snack','Busy mornings','Weight loss','Muscle building'],
    ingredients:[
      '1 cup (170g) non-fat Greek yogurt',
      '½ cup berries (strawberries, blueberries, raspberries)',
      '½ banana, sliced',
      '¼ cup granola (low sugar)',
      '1 tbsp chia seeds',
      '1 tsp honey (optional)',
      '1 tbsp almond butter (optional)',
    ],
    steps:[
      'Add Greek yogurt to a bowl.',
      'Top with berries and banana.',
      'Add granola and chia seeds.',
      'Drizzle with honey and almond butter.',
      'Enjoy immediately and feel the difference!',
    ],
    proTip:'Use frozen berries for a thicker, ice-cream like texture!',
    swaps:['Swap berries with mango, pineapple or kiwi','Swap granola with oats or protein cereal','Add dark chocolate chips for an extra treat'],
    goals:{
      fatLoss:{ changes:['Skip granola or use less','Add more berries'], cal:300, protein:25 },
      recomp: { changes:['Use low sugar granola','Add chia seeds'], cal:360, protein:25 },
      muscle: { changes:['Add extra granola','Add 1 scoop protein powder','Add extra almond butter'], cal:520, protein:35 },
    },
  },
  {
    id:4, num:'RECIPE 23', category:'breakfast', img:'/r4.jpg',
    name:'AUREVA BREAKFAST BURRITO',
    tag:'Fuel Your Morning. Power Your Day.',
    cal:470, protein:38, carbs:42, fat:17, fiber:6, sugar:4,
    perfectFor:['Breakfast','Pre-workout fuel','Busy mornings','Meal prep','Weight management','Clean eating'],
    ingredients:[
      '1 whole wheat tortilla (high fiber)',
      '3 whole eggs',
      '2 egg whites',
      '3 oz lean turkey breast, diced',
      '¼ cup red bell pepper, diced',
      '¼ cup green bell pepper, diced',
      '¼ cup red onion, diced',
      '¼ cup black beans, drained',
      '1 tbsp olive oil',
      '2 tbsp salsa',
      'Salt & pepper to taste',
      'Optional: fresh cilantro',
    ],
    steps:[
      'In a bowl, whisk eggs and egg whites with salt and pepper.',
      'Heat olive oil in a skillet over medium heat. Add diced turkey and cook until browned, about 3 minutes.',
      'Add onion, bell peppers and cook for 2–3 minutes until soft.',
      'Add eggs and scramble everything together until fully cooked.',
      'Stir in black beans and salsa.',
      'Warm the tortilla for 20–30 seconds in a microwave.',
      'Add the filling to the center, fold in the sides and roll tightly.',
      'Enjoy hot and conquer your day!',
    ],
    proTip:'Make a batch and wrap in foil for an easy grab-and-go breakfast all week!',
    swaps:['Swap turkey for chicken or lean beef','Use low-fat cheese for extra flavor','Add avocado for healthy fats','Use hot salsa or pico de gallo for a kick','Add spinach or arugula for more greens'],
    goals:{
      fatLoss:{ changes:['Use 1 whole egg + 3 egg whites','Skip cheese','Load up on veggies','Use salsa instead of creamy sauces'], cal:410, protein:38 },
      recomp: { changes:['Follow recipe as written','Perfect balance of protein, carbs & fats'], cal:470, protein:38 },
      muscle: { changes:['Add ¼ avocado','Add extra cheese','Add side of Greek yogurt','Use larger tortilla'], cal:580, protein:45 },
    },
  },

  // ── BOWLS ──────────────────────────────────────────────────────────────────
  {
    id:5, num:'RECIPE 4', category:'bowls', img:'/r5.jpg',
    name:'GRILLED CHICKEN POWER PLATE',
    tag:'Lean. Clean. Strong.',
    cal:430, protein:40, carbs:40, fat:9, fiber:6, sugar:4,
    perfectFor:['Lunch or Dinner','Post-workout fuel','Weight loss','Muscle building','Meal prep','Busy lifestyles'],
    ingredients:[
      '1 grilled chicken breast (150g)',
      '½ cup cooked brown rice',
      '1 cup mixed vegetables (broccoli, bell peppers, onions)',
      '1 tbsp olive oil',
      '1 tsp garlic powder',
      '1 tsp paprika',
      'Salt & black pepper to taste',
      'Lemon juice (optional)',
    ],
    steps:[
      'Season chicken with garlic powder, paprika, salt and pepper.',
      'Heat olive oil in a grill pan or skillet over medium heat.',
      'Grill chicken for 6–7 minutes per side until fully cooked.',
      'Steam or sauté vegetables until tender and vibrant.',
      'Serve chicken with brown rice and veggies. Squeeze lemon on top.',
      'Enjoy a meal that fuels your goals!',
    ],
    proTip:'Marinate your chicken for 15–30 minutes for maximum flavor!',
    swaps:['Swap chicken with turkey, salmon or tofu','Swap brown rice with quinoa or sweet potato','Add hot sauce or mustard for extra flavor'],
    goals:{
      fatLoss:{ changes:['Use less rice (¼ cup)','Load up on vegetables','Use cooking spray instead of oil'], cal:330, protein:38 },
      recomp: { changes:['Follow the recipe as is','Great balance of protein, carbs & healthy fats'], cal:430, protein:40 },
      muscle: { changes:['Add ½ avocado','Add extra rice (½ cup)','Add a side of Greek yogurt'], cal:580, protein:50 },
    },
  },
  {
    id:6, num:'RECIPE 5', category:'bowls', img:'/r6.jpg',
    name:'TURKEY & SWEET POTATO POWER BOWL',
    tag:'Clean ingredients. Big results.',
    cal:450, protein:35, carbs:42, fat:12, fiber:7, sugar:6,
    perfectFor:['Lunch or Dinner','Meal prep','Post-workout','Weight loss','Muscle building'],
    ingredients:[
      '1 lb (450g) ground turkey (93% lean)',
      '1 medium sweet potato, diced',
      '1 cup broccoli florets',
      '½ red bell pepper, sliced',
      '1 tbsp olive oil',
      '2 cloves garlic, minced',
      '1 tsp paprika',
      '1 tsp Italian seasoning',
      'Salt & black pepper to taste',
      'Optional: hot sauce or sriracha',
    ],
    steps:[
      'Preheat oven to 400°F (200°C).',
      'Toss sweet potato cubes with ½ tbsp olive oil, salt, pepper and paprika. Roast for 20–25 minutes until tender.',
      'Heat remaining olive oil in a skillet over medium heat.',
      'Add garlic and cook for 30 seconds.',
      'Add ground turkey and cook until fully browned. Season with Italian seasoning, salt and pepper.',
      'Steam or sauté broccoli and bell pepper until tender.',
      'Assemble in a bowl and enjoy!',
    ],
    proTip:'Roast sweet potatoes in advance for even faster meals!',
    swaps:['Swap turkey for chicken or lean beef','Swap sweet potato for brown rice or quinoa','Add avocado for healthy fats'],
    goals:{
      fatLoss:{ changes:['Use ½ sweet potato','Add extra veggies','Focus on lean protein'], cal:380, protein:35 },
      recomp: { changes:['Keep the recipe as is','Add ¼ cup quinoa'], cal:450, protein:35 },
      muscle: { changes:['Add ½ cup cooked quinoa','Add extra avocado','Add side of Greek yogurt'], cal:620, protein:45 },
    },
  },
  {
    id:7, num:'RECIPE 6', category:'bowls', img:'/r7.jpg',
    name:'LEAN BEEF & RICE POWER BOWL',
    tag:'Simple. Filling. Built for results.',
    cal:470, protein:35, carbs:45, fat:12, fiber:6, sugar:5,
    perfectFor:['Lunch or Dinner','Meal prep','Post-workout','Weight loss','Muscle building'],
    ingredients:[
      '1 lb (450g) extra lean ground beef (95% lean)',
      '1 cup cooked brown rice',
      '1 cup mixed vegetables (bell peppers, onions, green beans)',
      '1 tbsp olive oil',
      '2 cloves garlic, minced',
      '1 tsp onion powder',
      '1 tsp paprika',
      'Salt & black pepper to taste',
      'Optional: low sodium soy sauce or hot sauce',
    ],
    steps:[
      'Heat olive oil in a large skillet over medium heat.',
      'Add garlic and cook for 30 seconds.',
      'Add ground beef. Cook until browned, breaking it up as it cooks.',
      'Season with onion powder, paprika, salt and pepper.',
      'Add mixed vegetables and cook for 5–7 minutes until tender.',
      'Stir in soy sauce or hot sauce if using.',
      'Serve over cooked brown rice and enjoy!',
    ],
    proTip:'Use 93–95% lean beef for the best balance of flavor and nutrition!',
    swaps:['Swap beef for ground turkey, chicken or bison','Swap brown rice for quinoa or cauliflower rice','Add avocado for healthy fats'],
    goals:{
      fatLoss:{ changes:['Use cauliflower rice','Add more vegetables','Keep portions balanced'], cal:420, protein:35 },
      recomp: { changes:['Perfect balance of protein, carbs & healthy fats','Stay consistent with training'], cal:470, protein:35 },
      muscle: { changes:['Add ½ cup more rice','Add avocado','Add extra lean beef (¼ lb)'], cal:600, protein:45 },
    },
  },
  {
    id:8, num:'RECIPE 14', category:'bowls', img:'/r8.jpg',
    name:'CHICKEN & QUINOA POWER BOWL',
    tag:'Balanced. Delicious. Built for results.',
    cal:470, protein:35, carbs:42, fat:14, fiber:8, sugar:4,
    perfectFor:['Lunch or Dinner','Post-workout','Weight Management','Muscle Building','Clean Eating'],
    ingredients:[
      '6 oz (170g) chicken breast, diced',
      '½ cup uncooked quinoa',
      '½ cup black beans, rinsed',
      '½ cup corn (fresh, frozen or canned)',
      '½ red bell pepper, diced',
      '¼ red onion, diced',
      '½ avocado, sliced',
      '1 tbsp olive oil',
      '1 tbsp fresh lime juice',
      '1 tsp chili powder',
      '½ tsp cumin',
      '½ tsp garlic powder',
      'Salt & black pepper to taste',
      'Fresh cilantro (optional)',
    ],
    steps:[
      'Cook quinoa according to package instructions. Set aside.',
      'Heat ½ tbsp olive oil in a skillet over medium heat.',
      'Season chicken with chili powder, cumin, garlic powder, salt and pepper.',
      'Add chicken to the pan and cook for 6–8 minutes, until fully cooked. Remove from heat.',
      'In a large bowl, combine cooked quinoa, black beans, corn, bell pepper and red onion.',
      'Add lime juice and remaining olive oil. Toss gently to combine.',
      'Top with sliced chicken and avocado.',
      'Garnish with fresh cilantro and enjoy!',
    ],
    proTip:'Rinse quinoa before cooking for the best flavor and texture.',
    swaps:['Swap chicken with shrimp, tofu or lean beef','Swap quinoa with brown rice, farro or cauliflower rice','Add hot sauce or salsa for a kick'],
    goals:{
      fatLoss:{ changes:['Use cauliflower rice instead of quinoa','Reduce avocado to ¼','Add extra greens'], cal:380, protein:34 },
      recomp: { changes:['Perfect balance of protein, carbs & healthy fats','Great for recovery & energy'], cal:470, protein:35 },
      muscle: { changes:['Add extra chicken or shrimp','Top with avocado or olive oil','Increase portion sizes'], cal:620, protein:45 },
    },
  },
  {
    id:9, num:'RECIPE 11', category:'bowls', img:'/r9.jpg',
    name:'TURKEY & SWEET POTATO POWER BOWL',
    tag:'Wholesome ingredients. Powerful you.',
    cal:490, protein:34, carbs:46, fat:14, fiber:8, sugar:6,
    perfectFor:['Lunch or Dinner','Meal Prep','Post-workout','Weight Management','Muscle Building'],
    ingredients:[
      '6 oz (170g) ground turkey (93% lean)',
      '1 medium sweet potato, diced',
      '1 cup cooked quinoa',
      '½ cup black beans, rinsed',
      '½ cup corn (fresh, frozen or canned)',
      '1 cup baby spinach',
      '½ red bell pepper, sliced',
      '½ avocado, sliced',
      '1 tbsp olive oil',
      '1 tsp chili powder',
      '½ tsp garlic powder',
      '½ tsp cumin',
      'Salt & black pepper to taste',
      'Optional: lime wedges & fresh cilantro',
    ],
    steps:[
      'Preheat oven to 400°F (200°C).',
      'Toss diced sweet potato with ½ tbsp olive oil, salt and pepper. Roast for 20–25 minutes until tender.',
      'Heat remaining olive oil in a skillet over medium heat.',
      'Add ground turkey, chili powder, garlic powder, cumin, salt and pepper.',
      'Cook until turkey is fully cooked, breaking it up as it cooks.',
      'In a bowl, add cooked quinoa as the base.',
      'Top with turkey, roasted sweet potato, black beans, corn, spinach, bell pepper and avocado.',
      'Squeeze lime juice on top, garnish with cilantro and enjoy!',
    ],
    proTip:'Roast extra sweet potatoes for quick meals all week!',
    swaps:['Swap turkey for chicken, tofu or lean beef','Swap quinoa for brown rice, farro or cauliflower rice','Add hot sauce or salsa for a flavor boost'],
    goals:{
      fatLoss:{ changes:['Use cauliflower rice','Reduce avocado to ¼','Add extra greens'], cal:420, protein:34 },
      recomp: { changes:['Perfect balance of protein, carbs & healthy fats','Great post-workout meal'], cal:490, protein:34 },
      muscle: { changes:['Add extra quinoa or brown rice','Add extra turkey (2–3 oz)','Top with Greek yogurt or cheese'], cal:620, protein:45 },
    },
  },
  {
    id:10, num:'RECIPE 17', category:'bowls', img:'/r10.jpg',
    name:'COSTA RICAN CHICKEN BOWL',
    tag:'Bold flavors. Clean ingredients. Real results.',
    cal:440, protein:33, carbs:42, fat:12, fiber:8, sugar:5,
    perfectFor:['Lunch or Dinner','Post-workout','Weight Management','Muscle Building','Clean Eating'],
    ingredients:[
      '6 oz (170g) grilled chicken breast, sliced',
      '½ cup cooked brown rice',
      '½ cup black beans, rinsed',
      '½ cup corn (fresh or frozen)',
      '½ cup diced red bell pepper',
      '¼ cup diced red onion',
      '¼ avocado, sliced',
      '1 tbsp chopped cilantro',
      '1 tbsp lime juice',
      '1 tsp olive oil',
      '1 tsp garlic powder',
      'Salt & black pepper to taste',
      'SAUCE: 2 tbsp plain Greek yogurt, 1 tbsp lime juice, 1 tsp hot sauce (optional)',
    ],
    steps:[
      'Cook brown rice according to package instructions. Set aside.',
      'Season chicken with garlic powder, salt, pepper and a squeeze of lime. Grill or cook for 6–7 minutes per side until fully cooked. Slice.',
      'In a small bowl, whisk together all sauce ingredients until smooth.',
      'In a large bowl, build your bowl: add rice, black beans, corn, red bell pepper, red onion and cilantro.',
      'Top with sliced chicken and avocado.',
      'Drizzle sauce over everything and squeeze lime juice on top.',
      'Season with salt and pepper to taste. Enjoy!',
    ],
    proTip:'Marinate chicken in lime juice, garlic and a pinch of salt 30 minutes before cooking for extra flavor.',
    swaps:['Swap chicken with grilled shrimp, steak or tofu','Use quinoa, cauliflower rice or farro instead','Try salsa, hot sauce or chimichurri for a flavor twist'],
    goals:{
      fatLoss:{ changes:['Use cauliflower rice','Add more non-starchy veggies','Use light sauce (less yogurt)'], cal:360, protein:32 },
      recomp: { changes:['Perfect balance of protein, carbs & fats','Great for post-workout meals'], cal:440, protein:33 },
      muscle: { changes:['Add extra chicken or shrimp','Increase portion of rice','Add a side of sweet potato'], cal:560, protein:40 },
    },
  },
  {
    id:11, num:'RECIPE 16', category:'bowls', img:'/r11.jpg',
    name:'TOFU & BROWN RICE POWER BOWL',
    tag:'Plant-powered. Protein-packed. Purpose-fueled.',
    cal:390, protein:28, carbs:49, fat:14, fiber:7, sugar:6,
    perfectFor:['Lunch or Dinner','Post-workout','Weight Management','Muscle Building','Clean Eating'],
    ingredients:[
      '1 cup (200g) extra firm tofu, pressed & cubed',
      '1 cup cooked brown rice',
      '½ cup edamame, shelled',
      '½ cup shredded purple cabbage',
      '½ cup shredded carrots',
      '¼ cucumber, sliced',
      '¼ avocado, sliced',
      '1 green onion, chopped',
      '1 tbsp sesame seeds (optional)',
      '1 tbsp olive oil',
      'SAUCE: 2 tbsp tahini, 1 tbsp low-sodium soy sauce, 1 tbsp maple syrup, 1 tbsp rice vinegar, 1 tsp sesame oil, 1–2 tbsp warm water, pinch garlic powder',
    ],
    steps:[
      'Cook brown rice according to package instructions. Set aside.',
      'Press tofu, then cut into cubes. Toss with a pinch of salt, pepper and 1 tsp soy sauce.',
      'Heat olive oil in a non-stick skillet over medium-high heat.',
      'Add tofu and cook for 8–10 minutes, turning occasionally, until golden and crispy. Remove from heat.',
      'In a small bowl, whisk together all sauce ingredients until smooth. Add water as needed.',
      'Assemble your bowl: add brown rice as the base.',
      'Top with tofu, edamame, cabbage, carrots, cucumber, avocado and green onions.',
      'Drizzle with sauce and sprinkle with sesame seeds. Enjoy!',
    ],
    proTip:'Press tofu for at least 15 minutes to remove excess water for better texture.',
    swaps:['Swap tofu for tempeh, chickpeas or grilled chicken','Use quinoa, farro or cauliflower rice instead','Skip avocado or add hummus for creaminess','Try peanut sauce or vinaigrette instead'],
    goals:{
      fatLoss:{ changes:['Use cauliflower rice','Reduce avocado to ⅛','Use light sauce (less tahini)'], cal:320, protein:26 },
      recomp: { changes:['Perfect balance of protein, carbs & fats','Helps rebuild and aid recovery'], cal:390, protein:28 },
      muscle: { changes:['Add extra tofu or tempeh','Add nuts or seeds','Increase portion of brown rice'], cal:470, protein:34 },
    },
  },
  {
    id:12, num:'RECIPE 18', category:'bowls', img:'/r12.jpg',
    name:'CASADO CON CARNE AUREVA',
    tag:'Traditional Costa Rican Comfort Food. High Protein Edition.',
    cal:520, protein:42, carbs:45, fat:18, fiber:10, sugar:0,
    perfectFor:['Lunch or Dinner','Post-workout','Muscle Building','High Performance'],
    ingredients:[
      'CARNE: 170g (6 oz) flank steak or sirloin, 1 tsp olive oil, 2 garlic cloves minced, ½ tsp cumin, ½ tsp oregano, salt & pepper',
      'RICE: ½ cup cooked white rice',
      'BLACK BEANS: ½ cup cooked black beans, ¼ cup bean broth, ¼ tsp cumin',
      'PICO DE GALLO: 1 tomato diced, ¼ red onion diced, fresh cilantro, juice of ½ lime, salt',
      'SWEET PLANTAIN: ½ ripe plantain, cooking spray or 1 tsp olive oil',
      'SALAD: lettuce, cucumber, carrot',
    ],
    steps:[
      'COOK THE STEAK: Season with garlic, cumin, oregano, salt & pepper. Grill or pan-sear 3–4 minutes per side. Rest 5 minutes. Slice thinly.',
      'HEAT THE BEANS: Warm black beans with bean broth and cumin. Simmer for 5 minutes.',
      'PREPARE PICO DE GALLO: Mix tomato, onion, cilantro, lime juice and salt. Set aside.',
      'COOK PLANTAINS: Slice ripe plantain diagonally. Cook in a skillet until golden brown on both sides.',
      'ASSEMBLE THE CASADO: Plate with carne, rice, black beans, sweet plantains, salad and pico de gallo. Serve with fresh lime wedges.',
    ],
    proTip:'The secret to an authentic Costa Rican casado is balance: A little rice. A little beans. A little salad. A little sweet plantain. Great steak. Nothing fancy. Everything delicious.',
    swaps:['Use chicken or turkey instead of beef','Use brown rice instead of white','Skip plantain for fat loss'],
    goals:{
      fatLoss:{ changes:['Use 4 oz steak','Half portion rice','Extra salad'], cal:420, protein:38 },
      recomp: { changes:['Follow recipe as written'], cal:520, protein:42 },
      muscle: { changes:['8 oz steak','Double rice','Double beans','Full plantain'], cal:760, protein:60 },
    },
  },

  // ── FISH & SEAFOOD ─────────────────────────────────────────────────────────
  {
    id:13, num:'RECIPE 7', category:'fish', img:'/r13.jpg',
    name:'SEARED SALMON & ASPARAGUS BOWL',
    tag:'Simple. Clean. Premium fuel.',
    cal:460, protein:40, carbs:35, fat:16, fiber:6, sugar:3,
    perfectFor:['Lunch or Dinner','Post-workout','Weight loss','Muscle building','Meal prep'],
    ingredients:[
      '6 oz (170g) salmon fillet',
      '1 cup cooked brown rice',
      '1 bunch asparagus',
      '1 tbsp olive oil',
      '2 cloves garlic, minced',
      '½ tsp lemon juice',
      '½ tsp garlic powder',
      '½ tsp paprika',
      'Salt & black pepper to taste',
      'Optional: chili flakes or dill',
    ],
    steps:[
      'Preheat oven to 400°F (200°C).',
      'Season salmon with garlic powder, paprika, salt and pepper.',
      'Heat olive oil in a skillet over medium-high heat.',
      'Sear salmon skin-side down for 3–4 minutes. Flip and cook for another 3–4 minutes until cooked through.',
      'In the same pan, add garlic and asparagus. Sauté for 5–6 minutes until tender.',
      'Serve salmon with asparagus and brown rice. Squeeze lemon on top.',
    ],
    proTip:'Let salmon sit for 5 minutes after cooking for maximum juiciness!',
    swaps:['Swap salmon with cod, tilapia or trout','Swap brown rice with quinoa or cauliflower rice','Swap asparagus with green beans or broccoli','Add avocado for healthy fats'],
    goals:{
      fatLoss:{ changes:['Keep portions moderate','Use cauliflower rice','Load up on vegetables'], cal:390, protein:40 },
      recomp: { changes:['Perfect balance of protein, carbs & healthy fats','Great for maintaining muscle'], cal:460, protein:40 },
      muscle: { changes:['Add ½ cup more rice','Add avocado','Add a side of fruit','Increase portion size'], cal:620, protein:45 },
    },
  },
  {
    id:14, num:'RECIPE 13', category:'fish', img:'/r14.jpg',
    name:'SALMON & ASPARAGUS WITH DIJON',
    tag:'Clean energy. Healthy fats. Peak performance.',
    cal:430, protein:36, carbs:12, fat:24, fiber:4, sugar:3,
    perfectFor:['Lunch or Dinner','Post-workout','Weight Management','Muscle Building','Healthy Lifestyle'],
    ingredients:[
      '6 oz (170g) salmon fillet',
      '1 bunch asparagus, trimmed',
      '1 cup cherry tomatoes, halved',
      '2 cloves garlic, minced',
      '1 tbsp olive oil',
      '1 tsp lemon zest',
      '1 tbsp lemon juice',
      '1 tsp Dijon mustard',
      '½ tsp garlic powder',
      'Salt & black pepper to taste',
      'Optional: fresh dill or parsley',
    ],
    steps:[
      'Preheat oven to 425°F (220°C).',
      'Toss asparagus and cherry tomatoes with 1 tbsp olive oil, salt, pepper and garlic powder. Spread on a baking sheet and roast for 12–15 minutes.',
      'Season salmon with salt, pepper, lemon zest and garlic.',
      'Heat remaining olive oil in a non-stick skillet over medium-high heat.',
      'Sear salmon skin-side down for 4–5 minutes, then flip and cook for another 3–4 minutes until cooked through.',
      'In a small bowl, whisk lemon juice and Dijon mustard.',
      'Drizzle sauce over salmon. Serve with roasted veggies and garnish with dill.',
    ],
    proTip:'Pat salmon dry before cooking for a perfect sear.',
    swaps:['Swap salmon with shrimp, tilapia or cod','Use green beans, zucchini or broccoli instead','Add a side of roasted sweet potato','Use tahini or Greek yogurt sauce instead of Dijon'],
    goals:{
      fatLoss:{ changes:['Use cooking spray instead of oil','Add more veggies','Skip the sauce or use lemon only'], cal:360, protein:34 },
      recomp: { changes:['Perfect balance of protein, fats & carbs','Great for recovery & energy'], cal:430, protein:36 },
      muscle: { changes:['Add quinoa or brown rice','Increase portion of salmon','Add nuts or seeds'], cal:560, protein:46 },
    },
  },,
  {
    id:16, num:'RECIPE 15', category:'fish', img:'/r16.jpg',
    name:'SHRIMP & VEGGIE POWER SKILLET',
    tag:'Simple ingredients. Big nutrition. Real results.',
    cal:340, protein:32, carbs:18, fat:12, fiber:5, sugar:5,
    perfectFor:['Lunch or Dinner','Post-workout','Weight Management','Muscle Building','Busy Weeknights'],
    ingredients:[
      '1 lb (450g) raw shrimp, peeled & deveined',
      '2 cups broccoli florets',
      '1 red bell pepper, sliced',
      '1 yellow bell pepper, sliced',
      '1 zucchini, sliced',
      '½ red onion, sliced',
      '3 cloves garlic, minced',
      '1 tbsp olive oil or avocado oil',
      '1 tbsp low-sodium soy sauce',
      '1 tsp lemon juice',
      '1 tsp smoked paprika',
      '½ tsp garlic powder',
      '¼ tsp red pepper flakes (optional)',
      'Salt & black pepper to taste',
      'Optional: sesame seeds & green onions',
    ],
    steps:[
      'Heat ½ tbsp oil in a large skillet or wok over medium-high heat.',
      'Add shrimp, season with paprika, garlic powder, salt and pepper. Cook for 2–3 minutes per side until pink and cooked through. Remove and set aside.',
      'In the same skillet, add remaining oil. Add garlic and onion. Sauté for 1 minute until fragrant.',
      'Add broccoli and bell peppers. Stir-fry for 4–5 minutes until slightly tender.',
      'Add zucchini and cook for another 2 minutes.',
      'Return shrimp to the skillet.',
      'Add soy sauce, lemon juice and red pepper flakes. Toss everything together.',
      'Cook for 1–2 minutes more. Adjust seasoning and serve hot!',
    ],
    proTip:'Pat shrimp dry before seasoning for the best sear.',
    swaps:['Use chicken breast or turkey instead of shrimp','Swap zucchini with mushrooms or green beans','Serve over brown rice, quinoa or cauliflower rice','Use coconut aminos instead of soy sauce'],
    goals:{
      fatLoss:{ changes:['Serve as is for a low-calorie meal','Skip the rice or noodles','Add extra vegetables'], cal:300, protein:32 },
      recomp: { changes:['Add a side of quinoa or brown rice','Great post-workout meal'], cal:430, protein:32 },
      muscle: { changes:['Add quinoa or rice','Top with avocado or nuts','Increase portion sizes'], cal:560, protein:38 },
    },
  },

  // ── STIR-FRIES ─────────────────────────────────────────────────────────────
  {
    id:17, num:'RECIPE 12', category:'stirfry', img:'/r17.jpg',
    name:'CLASSIC BEEF & BROCCOLI STIR-FRY',
    tag:'Bold flavors. Lean protein. Maximum fuel.',
    cal:420, protein:32, carbs:28, fat:16, fiber:6, sugar:8,
    perfectFor:['Lunch or Dinner','Post-workout','Weight Management','Muscle Building','Busy Weeknights'],
    ingredients:[
      '6 oz (170g) lean beef sirloin, thinly sliced',
      '2 cups broccoli florets',
      '1 red bell pepper, sliced',
      '½ cup snap peas',
      '¼ cup red onion, sliced',
      '2 cloves garlic, minced',
      '1 tsp fresh ginger, grated',
      '1 tbsp olive oil or avocado oil',
      'SAUCE: 2 tbsp low-sodium soy sauce, 1 tbsp oyster sauce, 1 tsp sesame oil, 1 tsp honey, ½ tsp cornstarch mixed with 2 tbsp water',
      'Optional: sesame seeds & green onions',
    ],
    steps:[
      'In a small bowl, whisk together all sauce ingredients. Set aside.',
      'Heat 1 tsp oil in a large skillet or wok over high heat.',
      'Add beef in a single layer and stir-fry for 2–3 minutes until browned. Remove and set aside.',
      'Add remaining oil. Add garlic, ginger and onion. Stir-fry for 30 seconds until fragrant.',
      'Add broccoli, bell pepper and snap peas. Stir-fry for 3–4 minutes until crisp-tender.',
      'Return beef to the pan. Pour sauce over everything and toss to coat.',
      'Cook for another 1–2 minutes until sauce thickens. Garnish and serve hot!',
    ],
    proTip:'Slice beef thin for tenderness and faster cooking.',
    swaps:['Swap beef with chicken breast or shrimp','Swap white rice with brown rice or quinoa','Swap broccoli with bok choy or green beans','Use coconut aminos instead of soy sauce'],
    goals:{
      fatLoss:{ changes:['Use minimal oil','Swap rice with cauliflower rice','Load up on extra veggies','Keep sauces light'], cal:360, protein:32 },
      recomp: { changes:['Perfect balance of protein, carbs & healthy fats','Great post-workout meal'], cal:420, protein:32 },
      muscle: { changes:['Add extra beef or chicken','Serve with brown rice or quinoa','Add a side of sweet potato'], cal:560, protein:45 },
    },
  },
  {
    id:18, num:'RECIPE 19', category:'stirfry', img:'/r18.jpg',
    name:'LEAN BEEF & RAINBOW VEGGIE STIR-FRY',
    tag:'High protein. Big flavor. Real results.',
    cal:390, protein:36, carbs:30, fat:13, fiber:6, sugar:6,
    perfectFor:['Lunch or Dinner','Post-workout','Weight Management','Muscle Building','Busy Weeknights'],
    ingredients:[
      '170g (6 oz) lean beef (sirloin or flank steak), thinly sliced',
      '1 tsp olive oil',
      '2 garlic cloves, minced',
      '1 tsp fresh ginger, grated',
      '1 cup broccoli florets',
      '1 red bell pepper, sliced',
      '1 yellow bell pepper, sliced',
      '1 cup snap peas',
      '1 small carrot, julienned',
      '2 green onions, sliced',
      '1 tbsp low-sodium soy sauce',
      '1 tbsp oyster sauce (optional)',
      '1 tsp sesame oil',
      '1 tsp honey or maple syrup',
      '½ tsp chili flakes (optional)',
      'Sesame seeds for garnish',
    ],
    steps:[
      'Slice beef thinly against the grain. Season lightly with salt and pepper.',
      'Heat olive oil in a large skillet or wok over medium-high heat.',
      'Add beef in a single layer and cook 2–3 minutes until browned. Remove and set aside.',
      'In the same pan, add garlic and ginger. Sauté for 30 seconds until fragrant.',
      'Add all vegetables and stir-fry for 4–5 minutes until crisp-tender.',
      'Return beef to the pan. Add soy sauce, oyster sauce, sesame oil, honey and chili flakes. Toss to coat.',
      'Cook for another 1–2 minutes. Top with green onions and sesame seeds. Serve hot!',
    ],
    proTip:'Slice the beef against the grain for maximum tenderness.',
    swaps:['Use chicken breast or shrimp instead of beef','Swap beef for tofu or tempeh','Serve over brown rice, quinoa or cauliflower rice','Try coconut aminos instead of soy sauce'],
    goals:{
      fatLoss:{ changes:['Serve over cauliflower rice','Use 1 tsp oil','Add extra veggies','Keep portions in check'], cal:320, protein:34 },
      recomp: { changes:['Follow the recipe as written','Perfect balance of protein & carbs'], cal:390, protein:36 },
      muscle: { changes:['Serve over brown rice or quinoa','Add extra beef or shrimp','Use 2 tsp oil','Increase portion size'], cal:560, protein:48 },
    },
  },

  // ── POWER PLATES ───────────────────────────────────────────────────────────
  {
    id:19, num:'RECIPE 18', category:'plates', img:'/r19.jpg',
    name:'STEAK & SWEET POTATO POWER PLATE',
    tag:'High protein. Complex carbs. Maximum performance.',
    cal:520, protein:40, carbs:45, fat:16, fiber:7, sugar:6,
    perfectFor:['Lunch or Dinner','Post-workout','Muscle Building','Strength Training','Recovery','High Performance'],
    ingredients:[
      '6 oz (170g) lean steak (sirloin, strip or flank)',
      '1 medium sweet potato, cubed',
      '1 cup green beans',
      '1 tbsp olive oil',
      '1 clove garlic, minced',
      '1 tsp rosemary or thyme',
      'Salt & black pepper to taste',
    ],
    steps:[
      'Preheat oven to 425°F (220°C).',
      'Toss sweet potato cubes with ½ tbsp olive oil, garlic, salt and pepper. Roast for 20–25 minutes until tender.',
      'Season steak with salt, pepper and rosemary.',
      'Heat remaining oil in a skillet over medium-high heat. Cook steak 3–4 minutes per side for medium (4–5 for well done). Let rest.',
      'Sauté green beans in a pan with a little olive oil and garlic for 5 minutes.',
      'Plate everything and enjoy!',
    ],
    proTip:'Always let your steak rest for 5 minutes before slicing for maximum juiciness.',
    swaps:['Swap steak with chicken or salmon','Use regular potato or brown rice instead','Swap green beans for asparagus or broccoli','Add chimichurri sauce for more flavor','Top with avocado slices'],
    goals:{
      fatLoss:{ changes:['Use leaner steak','Add even more non-starchy veggies','Keep portions balanced'], cal:400, protein:36 },
      recomp: { changes:['Follow recipe as written','Perfect balance of protein, carbs & fats'], cal:520, protein:40 },
      muscle: { changes:['Add extra steak or shrimp','Increase portion of rice','Drizzle with olive oil','Add a side of sweet potato'], cal:650, protein:48 },
    },
  },
  {
    id:20, num:'RECIPE 10', category:'plates', img:'/r20.jpg',
    name:'EGG WHITE & SPINACH POWER SCRAMBLE',
    tag:'Light. Protein-packed. Start strong.',
    cal:310, protein:30, carbs:12, fat:12, fiber:4, sugar:4,
    perfectFor:['Breakfast','Post-workout','Weight Management','Clean Eating','Muscle Building','Busy Mornings'],
    ingredients:[
      '1 cup egg whites (about 6–7 eggs)',
      '1 cup fresh spinach, chopped',
      '¼ cup cherry tomatoes, halved',
      '¼ cup red onion, diced',
      '1 clove garlic, minced',
      '1 tsp olive oil or cooking spray',
      '¼ tsp turmeric (optional)',
      'Salt & black pepper to taste',
      'Optional: sprinkle of feta cheese',
    ],
    steps:[
      'Heat olive oil in a non-stick skillet over medium heat.',
      'Add garlic and onion. Sauté for 1–2 minutes until fragrant.',
      'Add spinach and cook until wilted, about 1–2 minutes.',
      'Pour in egg whites. Stir gently and cook on medium-low heat.',
      'Add cherry tomatoes, turmeric, salt and pepper.',
      'Cook for 4–6 minutes, stirring occasionally, until eggs are set and lightly fluffy.',
      'Remove from heat. Add feta if using. Serve warm and enjoy!',
    ],
    proTip:'Add a slice of whole grain toast or fruit for a complete meal.',
    swaps:['Add cooked shrimp or grilled chicken','Use mushrooms instead of tomatoes','Swap spinach with kale or arugula','Add avocado on the side for healthy fats'],
    goals:{
      fatLoss:{ changes:['Use egg whites only','Skip the cheese','Add extra veggies','Keep portions balanced'], cal:280, protein:30 },
      recomp: { changes:['Add whole grain toast or oatmeal on the side','Include healthy fats like avocado'], cal:380, protein:30 },
      muscle: { changes:['Add turkey or chicken on the side','Include quinoa or brown rice','Add a fruit smoothie or banana'], cal:500, protein:40 },
    },
  },

  // ── WRAPS ──────────────────────────────────────────────────────────────────
  {
    id:21, num:'RECIPE 19', category:'wraps', img:'/r21.jpg',
    name:'HIGH PROTEIN WRAP',
    tag:'Quick. Portable. Delicious. Results.',
    cal:420, protein:35, carbs:34, fat:14, fiber:8, sugar:4,
    perfectFor:['Lunch or Dinner','Post-workout','Weight Management','Muscle Building','Clean Eating','Busy Lifestyles'],
    ingredients:[
      '1 whole wheat wrap (high fiber)',
      '170g (6 oz) grilled chicken breast, sliced',
      '1 cup romaine lettuce, chopped',
      '½ cup diced red bell pepper',
      '¼ cup red onion, sliced',
      '¼ cup cucumber, diced',
      '2 tbsp shredded carrots',
      '2 tbsp hummus or Greek yogurt',
      '1 tsp olive oil',
      'Salt & pepper to taste',
      'Optional: hot sauce or mustard',
    ],
    steps:[
      'Season grilled chicken with salt, pepper and your favorite spices.',
      'In a small bowl, mix hummus or Greek yogurt with olive oil.',
      'Lay the wrap flat and spread the hummus or yogurt mixture evenly.',
      'Layer lettuce, chicken, bell pepper, onion, cucumber and shredded carrots.',
      'Add hot sauce or mustard if using.',
      'Roll the wrap tightly, tucking in the sides.',
      'Slice in half and enjoy!',
    ],
    proTip:'Warm the wrap for 10 seconds in the microwave for extra flavor and easier rolling.',
    swaps:['Swap chicken for turkey, shrimp or lean beef','Use avocado or guacamole instead of hummus','Use a low-carb tortilla or lettuce wrap','Add spinach or arugula for more greens','Switch up the flavor with salsa, tzatziki or tahini sauce'],
    goals:{
      fatLoss:{ changes:['Use low-carb wrap','Extra veggies','Light yogurt instead of hummus','Skip cheese','Add hot sauce'], cal:330, protein:33 },
      recomp: { changes:['Follow recipe as written','Perfect balance of protein, carbs & fats'], cal:420, protein:35 },
      muscle: { changes:['Add extra chicken','Add ¼ avocado','Add a slice of low-fat cheese','Use whole grain wrap'], cal:560, protein:45 },
    },
  },
  {
    id:22, num:'RECIPE 20', category:'wraps', img:'/r22.jpg',
    name:'BEEF POWER WRAP',
    tag:'Big flavor. Lean protein. Real results.',
    cal:450, protein:42, carbs:33, fat:16, fiber:8, sugar:4,
    perfectFor:['Lunch or Dinner','Post-workout','Muscle Building','Weight Management','Clean Eating','Busy Lifestyles'],
    ingredients:[
      '170g (6 oz) lean flank steak or sirloin, cooked and sliced',
      '1 whole wheat wrap (high fiber)',
      '1 cup romaine lettuce, chopped',
      '½ cup diced tomato',
      '¼ cup red onion, thinly sliced',
      '¼ avocado, sliced',
      '2 tbsp Greek yogurt',
      '1 tsp olive oil',
      '½ tsp garlic powder',
      '½ tsp smoked paprika',
      'Salt & pepper to taste',
      'Optional: hot sauce or mustard',
    ],
    steps:[
      'Season steak with garlic powder, smoked paprika, salt and pepper.',
      'Heat olive oil in a skillet over medium-high heat. Cook steak for 3–4 minutes per side (or until desired doneness). Rest for 5 minutes, then slice thinly.',
      'In a small bowl, mix Greek yogurt with a pinch of salt, pepper and hot sauce (if using). Set aside.',
      'Warm the wrap in a skillet or microwave for 10–15 seconds.',
      'Lay the wrap flat and spread the yogurt sauce in the center.',
      'Add lettuce, tomato, red onion, avocado and sliced steak.',
      'Roll it up tight, tuck in the sides and enjoy!',
    ],
    proTip:'Slice the steak thinly against the grain for maximum tenderness.',
    swaps:['Swap beef for grilled chicken or turkey','Use hummus instead of yogurt sauce','Add a slice of low-fat cheese for extra flavor','Add jalapeños for a spicy kick','Try chimichurri or balsamic glaze for a flavor boost'],
    goals:{
      fatLoss:{ changes:['Use 4 oz steak','Skip avocado','Extra veggies','Light sauce'], cal:380, protein:36 },
      recomp: { changes:['Follow recipe as written','Perfect balance of protein, carbs & fats'], cal:450, protein:42 },
      muscle: { changes:['Add extra steak','Add extra avocado','Add a side of sweet potato'], cal:620, protein:55 },
    },
  },
  {
    id:23, num:'RECIPE 21', category:'wraps', img:'/r23.jpg',
    name:'TUNA POWER WRAP',
    tag:'Simple ingredients. Serious results.',
    cal:360, protein:38, carbs:30, fat:9, fiber:6, sugar:3,
    perfectFor:['Lunch or Dinner','Post-workout','Weight Management','Muscle Building','Clean Eating','Busy Lifestyles'],
    ingredients:[
      '1 can (5 oz) tuna in water, drained',
      '2 tbsp plain Greek yogurt',
      '1 tsp Dijon mustard',
      '1 tsp lemon juice',
      '1 celery stalk, finely chopped',
      '¼ cup red onion, finely diced',
      '¼ cup cucumber, diced',
      '¼ cup shredded carrots',
      '1 cup romaine lettuce, chopped',
      '1 whole wheat wrap (high fiber)',
      'Salt & pepper to taste',
      'Optional: hot sauce or herbs',
    ],
    steps:[
      'In a bowl, mix tuna, Greek yogurt, Dijon mustard and lemon juice.',
      'Add celery, red onion, cucumber and carrots. Season with salt, pepper and any optional spices.',
      'Lay the wrap flat and add lettuce down the center.',
      'Spoon the tuna mixture on top of the lettuce.',
      'Roll it up tight, tucking in the sides.',
      'Slice in half and enjoy!',
    ],
    proTip:'Use tuna in water and Greek yogurt instead of mayo for a lean, high-protein version that still tastes amazing!',
    swaps:['Swap tuna for shredded chicken or canned salmon','Use hummus instead of yogurt for a different flavor','Add spinach or arugula for extra greens','Use whole grain wrap or low-carb wrap'],
    goals:{
      fatLoss:{ changes:['Use whole wheat wrap','Add extra veggies','Use light sauce','Keep portions in check'], cal:320, protein:36 },
      recomp: { changes:['Follow recipe as written','Perfect balance of protein, carbs & fats'], cal:360, protein:38 },
      muscle: { changes:['Add extra tuna','Add ¼ avocado or 1 tbsp olive oil','Add extra veggies or a side of fruit'], cal:480, protein:48 },
    },
  },
];

export const CATEGORIES = [
  { key:'all',       label:'ALL RECIPES',   icon:'🍽' },
  { key:'breakfast', label:'BREAKFAST',      icon:'🌅' },
  { key:'bowls',     label:'BOWLS',          icon:'🥣' },
  { key:'fish',      label:'FISH & SEAFOOD', icon:'🐟' },
  { key:'stirfry',   label:'STIR-FRY',       icon:'🥘' },
  { key:'plates',    label:'POWER PLATES',   icon:'💪' },
  { key:'wraps',     label:'WRAPS',          icon:'🌯' },
];
