// ─── Aureva Training System — All 28 Days Workout Data ───────────────────────

export const WORKOUTS = {
  1: {
    day:1, focus:"LOWER BODY STRENGTH",
    warmup:["5 min treadmill walk","Hip circles x 10","Bodyweight squats x 15","Banded lateral walks x 15/side"],
    exercises:[
      {name:"Hip Thrust",             sets:4, reps:"6–8",       rest:"90 sec"},
      {name:"Seated Leg Curl",         sets:3, reps:"10–12",     rest:"90 sec"},
      {name:"Bulgarian Split Squat",   sets:3, reps:"8–10/leg",  rest:"75 sec"},
      {name:"45° Back Extension",      sets:3, reps:"10–12",     rest:"75 sec"},
      {name:"Leg Press",               sets:3, reps:"10–12",     rest:"60 sec"},
      {name:"Walking Lunges",          sets:3, reps:"12 steps/leg",rest:"60 sec"},
      {name:"Cable Kickbacks",         sets:3, reps:"12–15/leg", rest:"60 sec"},
    ],
    core:[
      {name:"Plank",         sets:3, reps:"45 sec"},
      {name:"Reverse Crunch",sets:3, reps:"15"},
      {name:"Dead Bug",      sets:3, reps:"12/side"},
    ],
    cardio:"Incline Treadmill 10–20 min | Incline: 8–12 | Speed: 3–4",
    tempo:"2-1-1-0",
  },
  2: {
    day:2, focus:"UPPER BODY STRENGTH",
    warmup:["5 min treadmill walk","Arm circles x 15 fwd / x 15 back","Band pull-aparts x 20","Scapular push-ups x 10"],
    exercises:[
      {name:"Dumbbell Bench Press",    sets:4, reps:"6–8",       rest:"90 sec"},
      {name:"Lat Pulldown",            sets:3, reps:"8–10",      rest:"90 sec"},
      {name:"Seated Shoulder Press",   sets:3, reps:"8–10",      rest:"90 sec"},
      {name:"Single Arm Dumbbell Row", sets:3, reps:"10–12/arm", rest:"75 sec"},
      {name:"Chest Supported Row",     sets:3, reps:"10–12",     rest:"75 sec"},
      {name:"Dumbbell Lateral Raise",  sets:3, reps:"12–15",     rest:"60 sec"},
      {name:"Triceps Pushdown",        sets:3, reps:"12–15",     rest:"60 sec"},
      {name:"Bicep Curl",              sets:3, reps:"12–15",     rest:"60 sec"},
      {name:"Face Pull",               sets:3, reps:"12–15",     rest:"60 sec"},
    ],
    core:[
      {name:"Hanging Knee Raises",sets:3, reps:"12–15"},
      {name:"Dead Bug",           sets:3, reps:"12–15"},
      {name:"Russian Twist",      sets:3, reps:"20 (10/side)"},
    ],
    cardio:"Choose: Incline Treadmill 10–20 min | Stairmaster 10–15 min | Easy Walk 10 min",
    tempo:"2-1-1-0",
  },
  3: {
    day:3, focus:"PUSH DAY — CHEST, SHOULDERS, TRICEPS",
    warmup:["5 min treadmill walk","Arm circles x 15 fwd / x 15 back","Band pull-aparts x 20","Shoulder taps x 20","Push-up to down dog x 10"],
    exercises:[
      {name:"Barbell Bench Press",     sets:4, reps:"6–8",   rest:"90 sec"},
      {name:"Incline Dumbbell Press",  sets:3, reps:"8–10",  rest:"90 sec"},
      {name:"Machine Chest Press",     sets:3, reps:"8–10",  rest:"75 sec"},
      {name:"Seated Shoulder Press",   sets:3, reps:"8–10",  rest:"75 sec"},
      {name:"Lateral Raises",          sets:3, reps:"12–15", rest:"60 sec"},
      {name:"Cable Front Raises",      sets:3, reps:"12–15", rest:"60 sec"},
      {name:"Dips (Assisted if needed)",sets:3,reps:"8–12",  rest:"75 sec"},
      {name:"Tricep Rope Pushdown",    sets:3, reps:"10–12", rest:"60 sec"},
      {name:"Overhead Tricep Extension",sets:3,reps:"10–12", rest:"60 sec"},
    ],
    core:[
      {name:"Plank",         sets:3, reps:"45 sec"},
      {name:"Reverse Crunch",sets:3, reps:"15"},
      {name:"Russian Twist", sets:3, reps:"20 (10/side)"},
    ],
    cardio:"Choose: Incline Treadmill 10–20 min | Stairmaster 10–15 min | Easy Walk 10 min",
    tempo:"2-1-1-0",
  },
  4: {
    day:4, focus:"PULL DAY — BACK, BICEPS, REAR DELTS",
    warmup:["5 min treadmill walk","Arm circles x 15 fwd / x 15 back","Band pull-aparts x 20","Scapular retractions x 15","Light lat pulldown x 15"],
    exercises:[
      {name:"Pull-Ups / Assisted Pull-Ups", sets:4, reps:"6–10",      rest:"90 sec"},
      {name:"Bent Over Barbell Row",         sets:4, reps:"6–10",      rest:"90 sec"},
      {name:"Seated Cable Row",              sets:3, reps:"8–12",      rest:"75 sec"},
      {name:"Lat Pulldown (Wide Grip)",      sets:3, reps:"8–12",      rest:"75 sec"},
      {name:"Single Arm Dumbbell Row",       sets:3, reps:"10–12/arm", rest:"75 sec"},
      {name:"Face Pulls",                    sets:3, reps:"12–15",     rest:"60 sec"},
      {name:"Straight Arm Pulldown",         sets:3, reps:"12–15",     rest:"60 sec"},
      {name:"Rear Delt Fly (Cable/DB)",      sets:3, reps:"12–15",     rest:"60 sec"},
      {name:"Barbell or Dumbbell Curl",      sets:3, reps:"10–15",     rest:"60 sec"},
    ],
    core:[
      {name:"Hanging Knee Raises",     sets:3, reps:"12–15"},
      {name:"Cable Woodchopper/Side",  sets:3, reps:"12–15"},
      {name:"Plank",                   sets:3, reps:"45 sec"},
    ],
    cardio:"Choose: Incline Treadmill 10–20 min | Stairmaster 10–15 min | Easy Walk 10 min",
    tempo:"2-1-1-0",
  },
  5: {
    day:5, focus:"GLUTES & HAMSTRINGS",
    warmup:["5 min treadmill walk","Leg swings x 15 fwd / x 15 back","Hip circles x 10 each direction","Bodyweight squats x 15","Glute bridges x 15"],
    exercises:[
      {name:"Hip Thrust",         sets:4, reps:"6–10",      rest:"90 sec"},
      {name:"Romanian Deadlift",  sets:4, reps:"8–10",      rest:"90 sec"},
      {name:"Walking Lunges",     sets:3, reps:"10–12/leg", rest:"75 sec"},
      {name:"Lying Leg Curl",     sets:3, reps:"10–12",     rest:"75 sec"},
      {name:"Cable Kickbacks",    sets:3, reps:"12–15/leg", rest:"60 sec"},
      {name:"Glute Bridge (DB)",  sets:3, reps:"12–15",     rest:"60 sec"},
      {name:"Step-Ups",           sets:3, reps:"10–12/leg", rest:"60 sec"},
      {name:"Sumo Squat",         sets:3, reps:"12–15",     rest:"60 sec"},
      {name:"Donkey Kickbacks",   sets:3, reps:"15–20/leg", rest:"45 sec"},
    ],
    core:[
      {name:"Plank",              sets:3, reps:"45 sec"},
      {name:"Reverse Crunch",     sets:3, reps:"15"},
      {name:"Cable Woodchopper",  sets:3, reps:"12–15"},
    ],
    cardio:"Choose: Incline Treadmill 10–20 min | Stairmaster 10–15 min | Easy Walk 10 min",
    tempo:"2-1-1-0",
  },
  6: {
    day:6, focus:"CONDITIONING & CORE",
    warmup:["5 min light cardio (jog or bike)","Arm circles x 15 fwd / x 15 back","Leg swings x 15 each leg","Bodyweight squats x 15","High knees x 30 sec"],
    exercises:[
      {name:"Kettlebell Swings",  sets:4, reps:"15–20",   rest:"45 sec"},
      {name:"Battle Rope Slams",  sets:4, reps:"30 sec",  rest:"45 sec"},
      {name:"Burpees",            sets:3, reps:"10–15",   rest:"60 sec"},
      {name:"Mountain Climbers",  sets:3, reps:"40 sec",  rest:"45 sec"},
      {name:"Box Jumps",          sets:3, reps:"12–15",   rest:"60 sec"},
      {name:"Jump Squats",        sets:3, reps:"13–20",   rest:"45 sec"},
      {name:"TRX High Rows",      sets:3, reps:"12–15",   rest:"60 sec"},
      {name:"Medicine Ball Slams",sets:3, reps:"12–15",   rest:"45 sec"},
      {name:"Plank to Push-Up",   sets:3, reps:"10–12",   rest:"60 sec"},
    ],
    core:[
      {name:"Hanging Knee Raises",  sets:3, reps:"12–15"},
      {name:"Russian Twist/Side",   sets:3, reps:"20"},
      {name:"Plank Hold",           sets:3, reps:"45–60 sec"},
    ],
    cardio:"HIIT Treadmill 10–20 min | Incline: 10–15 | Speed: 3–5",
    tempo:"2-1-1-0",
  },
  7: {
    day:7, focus:"RECOVERY & MOBILITY",
    warmup:["5 min brisk walk","Arm circles x 15 fwd / x 15 back","Hip circles x 10 each direction","Leg swings x 15 each leg","Bodyweight squats x 15","Cat-cow stretch x 10"],
    exercises:[
      {name:"Foam Rolling Full Body",     sets:1, reps:"5–10 min", rest:"—"},
      {name:"Dynamic Hip Opener",         sets:3, reps:"10/side",  rest:"30 sec"},
      {name:"World's Greatest Stretch",   sets:3, reps:"6/side",   rest:"30 sec"},
      {name:"Glute Stretch (Figure 4)",   sets:3, reps:"30 sec/side",rest:"30 sec"},
      {name:"Hamstring Stretch",          sets:3, reps:"30 sec/side",rest:"30 sec"},
      {name:"Thoracic Spine Opener",      sets:3, reps:"10/side",  rest:"30 sec"},
      {name:"Scapular Wall Slides",       sets:3, reps:"12–15",    rest:"30 sec"},
      {name:"Deep Squat Hold",            sets:3, reps:"30–45 sec",rest:"30 sec"},
      {name:"Child's Pose + Reach",       sets:3, reps:"30 sec/side",rest:"30 sec"},
    ],
    core:[
      {name:"Dead Bug",    sets:3, reps:"10–12"},
      {name:"Bird Dog",    sets:3, reps:"10 each"},
      {name:"Side Plank",  sets:3, reps:"30 sec each side"},
    ],
    cardio:"Choose: Incline Treadmill 20–30 min | Easy Bike Ride 20–30 min | Easy Walk 10–15 min",
    tempo:"2-1-1-2",
  },
  8: {
    day:8, focus:"FULL BODY STRENGTH",
    warmup:["5 min treadmill walk","Arm circles x 15 fwd / x 15 back","Hip circles x 10 each direction","Bodyweight squats x 15","Leg swings x 15 each leg","Shoulder taps x 20"],
    exercises:[
      {name:"Goblet Squat",      sets:4, reps:"8–12",      rest:"90 sec"},
      {name:"Dumbbell Bench Press",sets:4,reps:"8–12",      rest:"90 sec"},
      {name:"Bent Over Row",     sets:4, reps:"8–12",      rest:"90 sec"},
      {name:"Romanian Deadlift", sets:3, reps:"10–12",     rest:"90 sec"},
      {name:"Shoulder Press",    sets:3, reps:"10–12",     rest:"75 sec"},
      {name:"Walking Lunges",    sets:3, reps:"12–15/leg", rest:"60 sec"},
      {name:"Lat Pulldown",      sets:3, reps:"10–12",     rest:"75 sec"},
      {name:"Cable Woodchopper", sets:3, reps:"12–15/side",rest:"60 sec"},
      {name:"Push-Up or Chest Dip",sets:3,reps:"10–15",    rest:"60 sec"},
    ],
    core:[
      {name:"Plank",         sets:3, reps:"45 sec"},
      {name:"Reverse Crunch",sets:3, reps:"15"},
      {name:"Russian Twist", sets:3, reps:"20 (each side)"},
    ],
    cardio:"Choose: Incline Treadmill 15–20 min | Stairmaster 15–20 min | Easy Walk 10–15 min",
    tempo:"2-1-1-0",
  },
  9: {
    day:9, focus:"TOTAL BODY POWER",
    warmup:["5 min treadmill walk","Arm circles x 15 fwd / x 15 back","Bodyweight squats x 15","Hip circles x 10 each direction","High knees x 30 sec","Leg swings x 15 each leg"],
    exercises:[
      {name:"Kettlebell Swings",  sets:4, reps:"15–20",   rest:"45 sec"},
      {name:"Push Press",         sets:4, reps:"8–10",    rest:"90 sec"},
      {name:"Goblet Squat",       sets:4, reps:"10–12",   rest:"75 sec"},
      {name:"Bent Over Row",      sets:4, reps:"10–12",   rest:"75 sec"},
      {name:"Walking Lunges",     sets:3, reps:"12–15/leg",rest:"60 sec"},
      {name:"Burpees",            sets:3, reps:"10–15",   rest:"60 sec"},
      {name:"Dumbbell Deadlift",  sets:3, reps:"10–12",   rest:"75 sec"},
      {name:"Mountain Climbers",  sets:3, reps:"30 sec",  rest:"45 sec"},
      {name:"Plank to Push-Up",   sets:3, reps:"10–12",   rest:"60 sec"},
    ],
    core:[
      {name:"Hanging Knee Raises",  sets:3, reps:"12–15"},
      {name:"Russian Twist/Side",   sets:3, reps:"20"},
      {name:"Plank Hold",           sets:3, reps:"45–60 sec"},
    ],
    cardio:"HIIT Treadmill 15–20 min | Incline: 8–12 | Speed: 3–5",
    tempo:"2-1-1-0",
  },
  10: {
    day:10, focus:"LOWER BODY STRENGTH",
    warmup:["5 min treadmill walk or bike","Hip circles x 15 each direction","Leg swings x 15 each leg","Bodyweight squats x 15","Glute bridges x 15"],
    exercises:[
      {name:"Back Squat",               sets:4, reps:"6–10",      rest:"90 sec"},
      {name:"Romanian Deadlift",         sets:4, reps:"8–12",      rest:"90 sec"},
      {name:"Leg Press",                 sets:3, reps:"10–12",     rest:"75 sec"},
      {name:"Walking Lunges",            sets:3, reps:"12–15/leg", rest:"60 sec"},
      {name:"Leg Curl (Lying or Seated)",sets:3, reps:"10–12",     rest:"60 sec"},
      {name:"Standing Calf Raise",       sets:4, reps:"12–15",     rest:"45 sec"},
      {name:"Glute Bridge (Barbell)",    sets:3, reps:"10–12",     rest:"60 sec"},
      {name:"Sled Push (Optional)",      sets:3, reps:"20–30 m",   rest:"60 sec"},
    ],
    core:[
      {name:"Hanging Leg Raises",    sets:3, reps:"12–15"},
      {name:"Weighted Russian Twist",sets:3, reps:"20/side"},
      {name:"Plank Hold",            sets:3, reps:"45–60 sec"},
    ],
    cardio:"Choose: Incline Treadmill 15–20 min | Stairmaster 20–30 min | HIIT Sprints 10 rounds",
    tempo:"2-1-1-0",
  },
  11: {
    day:11, focus:"UPPER BODY STRENGTH",
    warmup:["5 min treadmill walk or bike","Arm circles x 15 fwd / x 15 back","Band pull-aparts x 15","Shoulder taps x 20","Scapular push-ups x 15"],
    exercises:[
      {name:"Barbell Bench Press",    sets:4, reps:"6–10",       rest:"90 sec"},
      {name:"Seated Dumbbell Press",  sets:4, reps:"8–12",       rest:"90 sec"},
      {name:"Pull-Ups or Lat Pulldown",sets:4,reps:"8–12",       rest:"90 sec"},
      {name:"Single Arm Dumbbell Row",sets:3, reps:"10–12/arm",  rest:"75 sec"},
      {name:"Dumbbell Lateral Raises",sets:3, reps:"12–15",      rest:"60 sec"},
      {name:"Cable Row",              sets:3, reps:"12–15",      rest:"60 sec"},
      {name:"Face Pulls",             sets:3, reps:"12–15",      rest:"45 sec"},
      {name:"Bicep Curls",            sets:3, reps:"10–12",      rest:"60 sec"},
      {name:"Tricep Pushdowns",       sets:3, reps:"10–12",      rest:"60 sec"},
    ],
    core:[
      {name:"Hanging Knee Raises",    sets:3, reps:"12–15"},
      {name:"Cable Woodchoppers/side",sets:3, reps:"15/side"},
      {name:"Plank Hold",             sets:3, reps:"45–60 sec"},
    ],
    cardio:"Choose: Incline Treadmill 15–20 min | Stairmaster 20–30 min | HIIT Sprints 10 rounds",
    tempo:"2-1-1-0",
  },
  12: {
    day:12, focus:"GLUTES & HAMSTRINGS",
    warmup:["5 min treadmill walk or bike","Hip circles x 15 each direction","Leg swings x 15 each leg","Bodyweight squats x 15","Glute bridges x 15"],
    exercises:[
      {name:"Hip Thrust",               sets:4, reps:"8–12",       rest:"90 sec"},
      {name:"Romanian Deadlift",         sets:4, reps:"8–12",       rest:"90 sec"},
      {name:"Bulgarian Split Squat",     sets:3, reps:"10–12",      rest:"75 sec each leg"},
      {name:"Leg Curl (Lying or Seated)",sets:3, reps:"12–15",      rest:"60 sec"},
      {name:"Cable Pull Through",        sets:3, reps:"12–15",      rest:"60 sec"},
      {name:"Step-Ups",                  sets:3, reps:"12–15/leg",  rest:"60 sec"},
      {name:"Glute Kickbacks (Cable)",   sets:3, reps:"15–20/leg",  rest:"45 sec"},
      {name:"Squeeze Pulse",             sets:3, reps:"20",         rest:"45 sec"},
    ],
    core:[
      {name:"Hanging Leg Raises",    sets:3, reps:"12–15"},
      {name:"Weighted Russian Twist",sets:3, reps:"20/side"},
      {name:"Plank Hold",            sets:3, reps:"45–60 sec"},
    ],
    cardio:"Choose: Incline Treadmill 15–20 min | Stairmaster 20–30 min | HIIT Sprints 10 rounds",
    tempo:"2-1-1-0",
  },
  13: {
    day:13, focus:"CONDITIONING & CORE",
    warmup:["5 min light jog or jump rope","Arm circles x 15 fwd / x 15 back","Hip circles x 15 each direction","Bodyweight squats x 15","High knees x 30 sec"],
    exercises:[
      {name:"Battle Rope Slams",  sets:4, reps:"30 sec",  rest:"30 sec"},
      {name:"Jump Squats",        sets:4, reps:"15",      rest:"30 sec"},
      {name:"Mountain Climbers",  sets:4, reps:"30 sec",  rest:"30 sec"},
      {name:"Burpees",            sets:4, reps:"10–12",   rest:"45 sec"},
      {name:"Kettlebell Swings",  sets:4, reps:"20",      rest:"30 sec"},
      {name:"High Knees",         sets:4, reps:"30 sec",  rest:"30 sec"},
      {name:"Plank to Push-Up",   sets:3, reps:"10",      rest:"45 sec"},
      {name:"Russian Twists",     sets:3, reps:"20/side", rest:"30 sec"},
      {name:"V-Ups",              sets:3, reps:"15",      rest:"30 sec"},
    ],
    core:[
      {name:"Hanging Knee Raises",sets:3, reps:"12–15"},
      {name:"Bicycle Crunches",   sets:3, reps:"20/side"},
      {name:"Plank Hold",         sets:3, reps:"45–60 sec"},
    ],
    cardio:"HIIT Treadmill 15–20 min | Incline: 8–12 | Speed: 3–5",
    tempo:"2-1-1-0",
  },
  14: {
    day:14, focus:"RECOVERY & MOBILITY",
    warmup:["5 min brisk walk or easy bike","Arm circles x 15 each direction","Hip circles x 15 each direction","Cat-Cow x 10","Deep squat hold x 30 sec"],
    exercises:[
      {name:"World's Greatest Stretch",sets:3, reps:"6/side",        rest:"15–30 sec"},
      {name:"Hip Flexor Stretch",       sets:3, reps:"30 sec/side",  rest:"15–30 sec"},
      {name:"Glute Stretch",            sets:3, reps:"30 sec/side",  rest:"15–30 sec"},
      {name:"Thread the Needle",        sets:3, reps:"30 sec/side",  rest:"15–30 sec"},
      {name:"Hamstring Stretch",        sets:3, reps:"30 sec/side",  rest:"15–30 sec"},
      {name:"Couch Stretch",            sets:3, reps:"30 sec/side",  rest:"15–30 sec"},
      {name:"Child's Pose",             sets:3, reps:"60 sec",       rest:"15–30 sec"},
    ],
    core:[
      {name:"Dead Bug",      sets:3, reps:"10/side"},
      {name:"Bird Dog",      sets:3, reps:"10/side"},
      {name:"Forearm Plank", sets:3, reps:"30–45 sec"},
      {name:"Side Plank",    sets:3, reps:"30 sec/side"},
    ],
    cardio:"Choose: Incline Walk 20–30 min | Easy Bike 20–30 min | Elliptical 20–30 min",
    tempo:"2-1-1-2",
  },
  15: {
    day:15, focus:"FULL BODY STRENGTH",
    warmup:["5 min treadmill walk or bike","Arm circles x 15 fwd / x 15 back","Hip circles x 15 each direction","Leg swings x 15 each leg","Bodyweight squats x 15"],
    exercises:[
      {name:"Goblet Squat",      sets:4, reps:"8–12",     rest:"90 sec"},
      {name:"Push Press",        sets:4, reps:"8–10",     rest:"90 sec"},
      {name:"Bent Over Row",     sets:4, reps:"8–12",     rest:"90 sec"},
      {name:"Romanian Deadlift", sets:4, reps:"8–12",     rest:"90 sec"},
      {name:"Dumbbell Bench Press",sets:3,reps:"10–12",   rest:"75 sec"},
      {name:"Pull-Ups or Lat Pulldown",sets:3,reps:"10–12",rest:"75 sec"},
      {name:"Walking Lunges",    sets:3, reps:"12–15/leg",rest:"60 sec"},
      {name:"Dumbbell Thruster", sets:3, reps:"10–12",   rest:"60 sec"},
      {name:"Farmer's Carry",    sets:3, reps:"30–40 m",  rest:"60 sec"},
    ],
    core:[
      {name:"Hanging Knee Raises",sets:3, reps:"12–15"},
      {name:"Russian Twist",      sets:3, reps:"20/side"},
      {name:"Plank Hold",         sets:3, reps:"45–60 sec"},
    ],
    cardio:"Choose: HIIT Treadmill 15–20 min | Steady State 20–30 min | HIIT Sprints 10 rounds",
    tempo:"2-1-1-0",
  },
  16: {
    day:16, focus:"PULL & CORE STRENGTH",
    warmup:["5 min treadmill walk or bike","Arm circles x 15 fwd / x 15 back","Band pull-aparts x 15","Scapular pull-ups x 10","Hip circles x 15 each direction"],
    exercises:[
      {name:"Pull-Ups",               sets:4, reps:"6–10",      rest:"90 sec"},
      {name:"Bent Over Barbell Row",   sets:4, reps:"8–12",      rest:"90 sec"},
      {name:"Lat Pulldown",            sets:4, reps:"10–12",     rest:"75 sec"},
      {name:"Seated Cable Row",        sets:3, reps:"10–12",     rest:"75 sec"},
      {name:"Face Pulls",              sets:3, reps:"12–15",     rest:"60 sec"},
      {name:"Straight Arm Pulldown",   sets:3, reps:"12–15",     rest:"60 sec"},
      {name:"Reverse Fly (Rear Delt)", sets:3, reps:"12–15",     rest:"60 sec"},
      {name:"DB Bicep Curl",           sets:3, reps:"10–12",     rest:"60 sec"},
      {name:"Hammer Curl",             sets:3, reps:"10–12",     rest:"60 sec"},
    ],
    core:[
      {name:"Hanging Leg Raises",  sets:3, reps:"12–15"},
      {name:"Cable Woodchopper",   sets:3, reps:"12/side"},
      {name:"Plank Hold",          sets:3, reps:"45–60 sec"},
    ],
    cardio:"HIIT Treadmill 15–20 min | Incline: 8–12 | Speed: 3–5",
    tempo:"2-1-1-0",
  },
  17: {
    day:17, focus:"LOWER BODY POWER",
    warmup:["5 min brisk walk or bike","Leg swings x 15 each","Hip circles x 15 each direction","Bodyweight squats x 15","Calf raises x 20"],
    exercises:[
      {name:"Back Squat",           sets:4, reps:"4–6",      rest:"2 min"},
      {name:"Romanian Deadlift",     sets:4, reps:"6–8",      rest:"90 sec"},
      {name:"Bulgarian Split Squat", sets:3, reps:"8/leg",    rest:"90 sec"},
      {name:"Leg Press (Heavy)",     sets:3, reps:"8–10",     rest:"90 sec"},
      {name:"Box Jumps",             sets:4, reps:"5",        rest:"60 sec"},
      {name:"Walking Lunges",        sets:3, reps:"12/leg",   rest:"60 sec"},
      {name:"Standing Calf Raise",   sets:4, reps:"12–15",   rest:"60 sec"},
      {name:"Sled Push",             sets:4, reps:"20–30 m",  rest:"90 sec"},
      {name:"Sled Drag (Backward)",  sets:3, reps:"20–30 m",  rest:"90 sec"},
    ],
    core:[
      {name:"Hanging Leg Raises",      sets:3, reps:"12–15"},
      {name:"Russian Twist (Med Ball)",sets:3, reps:"20/side"},
      {name:"Plank Hold",              sets:3, reps:"45–60 sec"},
    ],
    cardio:"HIIT Treadmill 15–20 min | Incline: 8–12 | Speed: 3–5",
    tempo:"2-1-1-0",
  },
  18: {
    day:18, focus:"UPPER BODY HYPERTROPHY",
    warmup:["5 min treadmill walk or bike","Arm circles x 15 fwd / x 15 back","Shoulder dislocates x 15","Scapular push-ups x 10","Band pull-aparts x 15"],
    exercises:[
      {name:"Barbell Bench Press",   sets:4, reps:"8–12",  rest:"90 sec"},
      {name:"Pull-Ups or Lat Pulldown",sets:4,reps:"8–12", rest:"90 sec"},
      {name:"Incline Dumbbell Press",sets:3, reps:"10–15", rest:"75 sec"},
      {name:"Seated Cable Row",      sets:3, reps:"10–15", rest:"75 sec"},
      {name:"Dumbbell Shoulder Press",sets:3,reps:"10–15", rest:"75 sec"},
      {name:"Chest Fly (Cable or DB)",sets:3,reps:"12–15", rest:"60 sec"},
      {name:"Face Pulls",            sets:3, reps:"12–15", rest:"60 sec"},
      {name:"Dumbbell Bicep Curl",   sets:3, reps:"10–15", rest:"60 sec"},
      {name:"Cable Tricep Pushdown", sets:3, reps:"10–15", rest:"60 sec"},
    ],
    core:[
      {name:"Hanging Knee Raises",sets:3, reps:"12–15"},
      {name:"Cable Woodchopper",   sets:3, reps:"15/side"},
      {name:"Plank Hold",          sets:3, reps:"45–60 sec"},
    ],
    cardio:"HIIT Treadmill 15–20 min | Assault Bike 15–20 min | Rowing Machine 20–30 min",
    tempo:"2-1-2-0",
  },
  19: {
    day:19, focus:"GLUTES & HAMSTRINGS ADVANCED",
    warmup:["5 min treadmill walk or bike","Hip circles x 15 each direction","Bodyweight squats x 15","Leg swings x 15 each leg","Glute bridges x 20"],
    exercises:[
      {name:"Barbell Hip Thrust",  sets:4, reps:"8–12",      rest:"90 sec"},
      {name:"Romanian Deadlift",   sets:4, reps:"6–10",      rest:"90 sec"},
      {name:"Bulgarian Split Squat",sets:3,reps:"10–12",      rest:"75 sec/leg"},
      {name:"Cable Kickbacks",     sets:3, reps:"12–15/leg", rest:"60 sec"},
      {name:"Lying Leg Curl",      sets:3, reps:"10–15",     rest:"60 sec"},
      {name:"Dumbbell Step-Up",    sets:3, reps:"10–12/leg", rest:"60 sec"},
      {name:"Sumo Deadlift",       sets:3, reps:"8–10",      rest:"90 sec"},
      {name:"Glute Abduction",     sets:3, reps:"15–20",     rest:"60 sec"},
      {name:"Single Leg Hip Thrust",sets:3,reps:"12–15/leg", rest:"60 sec"},
    ],
    core:[
      {name:"Hanging Leg Raises",      sets:3, reps:"12–15"},
      {name:"Russian Twist (Med Ball)",sets:3, reps:"20/side"},
      {name:"Plank Hold",              sets:3, reps:"45–60 sec"},
    ],
    cardio:"HIIT Treadmill 15–20 min | StairMaster 20–30 min | Sled Push 6–10 rounds",
    tempo:"2-1-2-0",
  },
  20: {
    day:20, focus:"CONDITIONING & CORE ADVANCED",
    warmup:["5 min treadmill walk or bike","Arm circles x 15 fwd / x 15 back","Leg swings x 15 each leg","Hip circles x 15 each direction","Bodyweight squats x 15"],
    exercises:[
      {name:"Battle Rope Slams",    sets:4, reps:"30 sec",  rest:"30 sec"},
      {name:"Sled Push",            sets:4, reps:"30 m",    rest:"30 sec"},
      {name:"Kettlebell Swings",    sets:4, reps:"15",      rest:"30 sec"},
      {name:"Burpee Broad Jumps",   sets:4, reps:"10",      rest:"45 sec"},
      {name:"Mountain Climbers",    sets:4, reps:"30 sec",  rest:"30 sec"},
      {name:"Assault Bike",         sets:4, reps:"30 sec",  rest:"30 sec"},
      {name:"Jump Squats",          sets:4, reps:"15",      rest:"30 sec"},
      {name:"Plank to Push-Up",     sets:4, reps:"12",      rest:"30 sec"},
      {name:"High Knees Sprint",    sets:4, reps:"30 sec",  rest:"30 sec"},
    ],
    core:[
      {name:"Hanging Knee Raises",      sets:3, reps:"12–15"},
      {name:"Russian Twist (Med Ball)", sets:3, reps:"20/side"},
      {name:"Plank Hold",               sets:3, reps:"45–60 sec"},
    ],
    cardio:"HIIT Treadmill 15–20 min | Assault Bike 15–20 min | Rowing Machine 15–20 min",
    tempo:"2-1-2-0",
  },
  21: {
    day:21, focus:"RECOVERY & MOBILITY TRAINING",
    warmup:["5 min treadmill walk","Arm circles x 15 fwd / x 15 back","Leg swings x 15 each leg","Hip circles x 15 each direction","Bodyweight squats x 15"],
    exercises:[
      {name:"World's Greatest Stretch",sets:3, reps:"8/side",        rest:"30 sec"},
      {name:"Deep Lunge Reach",         sets:3, reps:"10/side",       rest:"30 sec"},
      {name:"Thread the Needle",        sets:3, reps:"10/side",       rest:"30 sec"},
      {name:"Pigeon Stretch",           sets:3, reps:"30 sec/side",   rest:"30 sec"},
      {name:"90/90 Hip Switch",         sets:3, reps:"12 reps",       rest:"30 sec"},
      {name:"Thoracic Rotation",        sets:3, reps:"10/side",       rest:"30 sec"},
      {name:"Hamstring Sweep",          sets:3, reps:"12/side",       rest:"30 sec"},
      {name:"Ankle Circles",            sets:3, reps:"15/side",       rest:"30 sec"},
      {name:"Hip Flexor Stretch",       sets:3, reps:"30 sec/side",   rest:"30 sec"},
    ],
    core:[
      {name:"Bird Dog",          sets:3, reps:"12/side"},
      {name:"Dead Bug",          sets:3, reps:"12/side"},
      {name:"Glute Bridge Hold", sets:3, reps:"30 sec"},
    ],
    cardio:"Choose: Incline Treadmill Walk 15–20 min | Stationary Bike 15–20 min | Rowing Machine 15–20 min",
    tempo:"2-1-2-0",
  },
  22: {
    day:22, focus:"PUSH POWER & UPPER BODY STRENGTH",
    warmup:["5 min treadmill walk","Arm circles x 15 fwd / x 15 back","Shoulder rolls x 15 each direction","Band pull-aparts x 15","Push-ups x 10"],
    exercises:[
      {name:"Barbell Bench Press",   sets:4, reps:"6–10",  rest:"60 sec"},
      {name:"Incline Dumbbell Press",sets:4, reps:"8–12",  rest:"60 sec"},
      {name:"Shoulder Press",        sets:4, reps:"8–12",  rest:"60 sec"},
      {name:"Dips",                  sets:3, reps:"8–12",  rest:"60 sec"},
      {name:"Cable Chest Fly",       sets:3, reps:"12–15", rest:"45 sec"},
      {name:"Lateral Raises",        sets:3, reps:"12–15", rest:"45 sec"},
      {name:"Tricep Pushdown",       sets:3, reps:"12–15", rest:"45 sec"},
      {name:"Overhead Tricep Ext.",  sets:3, reps:"10–15", rest:"45 sec"},
      {name:"Push-Up (AMRAP)",       sets:2, reps:"AMRAP", rest:"60 sec"},
    ],
    core:[
      {name:"Plank",            sets:3, reps:"45–60 sec"},
      {name:"Russian Twist",    sets:3, reps:"20/side"},
      {name:"Mountain Climbers",sets:3, reps:"30–45 sec"},
    ],
    cardio:"Choose: Incline Treadmill 15–20 min | Assault Bike 15–20 min | Rowing Machine 15–20 min",
    tempo:"2-1-2-0",
  },
  23: {
    day:23, focus:"LEGS & GLUTES STRENGTH",
    warmup:["5 min treadmill walk","Leg swings x 15 each leg","Bodyweight squats x 15","Glute bridges x 15","Ankle circles x 15 each direction"],
    exercises:[
      {name:"Barbell Back Squat",  sets:4, reps:"8–12",      rest:"90 sec"},
      {name:"Romanian Deadlift",   sets:4, reps:"8–12",      rest:"90 sec"},
      {name:"Walking Lunges",      sets:3, reps:"10/leg",    rest:"60 sec"},
      {name:"Leg Press",           sets:3, reps:"10–15",     rest:"60 sec"},
      {name:"Hip Thrust",          sets:4, reps:"10–15",     rest:"60 sec"},
      {name:"Leg Extension",       sets:3, reps:"12–15",     rest:"45 sec"},
      {name:"Leg Curl",            sets:3, reps:"12–15",     rest:"45 sec"},
      {name:"Standing Calf Raise", sets:4, reps:"15–20",     rest:"45 sec"},
      {name:"Seated Calf Raise",   sets:3, reps:"15–20",     rest:"45 sec"},
    ],
    core:[
      {name:"Hanging Knee Raises",sets:3, reps:"12–15"},
      {name:"Russian Twist",       sets:3, reps:"20/side"},
      {name:"Plank Hold",          sets:3, reps:"45–60 sec"},
    ],
    cardio:"HIIT Treadmill 15–20 min | Assault Bike 15–20 min | Rowing Machine 15–20 min",
    tempo:"2-1-2-0",
  },
  24: {
    day:24, focus:"PUSH, PULL & CORE POWER",
    warmup:["5 min treadmill walk","Arm circles x 15 fwd / x 15 back","Leg swings x 15 each leg","Hip circles x 15 each direction","Bodyweight squats x 15"],
    exercises:[
      {name:"Push-Up",              sets:4, reps:"8–12",  rest:"60 sec"},
      {name:"Bent Over Row",        sets:4, reps:"8–12",  rest:"60 sec"},
      {name:"Dumbbell Shoulder Press",sets:4,reps:"8–12", rest:"60 sec"},
      {name:"Goblet Squat",         sets:4, reps:"10–15", rest:"60 sec"},
      {name:"Lat Pulldown",         sets:3, reps:"10–15", rest:"60 sec"},
      {name:"Dumbbell Bench Press", sets:3, reps:"10–15", rest:"60 sec"},
      {name:"Seated Cable Row",     sets:3, reps:"10–15", rest:"45 sec"},
      {name:"Reverse Lunge",        sets:3, reps:"12/leg",rest:"45 sec"},
      {name:"Plank to Push-Up",     sets:3, reps:"10–12", rest:"45 sec"},
    ],
    core:[
      {name:"Hanging Knee Raises",sets:3, reps:"12–15"},
      {name:"Russian Twist",       sets:3, reps:"20/side"},
      {name:"Plank Hold",          sets:3, reps:"45–60 sec"},
    ],
    cardio:"HIIT Treadmill 15–20 min | Assault Bike 15–20 min | Rowing Machine 15–20 min",
    tempo:"2-1-2-0",
  },
  25: {
    day:25, focus:"TOTAL BODY STRENGTH",
    warmup:["5 min treadmill walk","Arm circles x 15 fwd / x 15 back","Leg swings x 15 each leg","Hip circles x 15 each direction","Bodyweight squats x 15"],
    exercises:[
      {name:"Goblet Squat",         sets:4, reps:"10–15",   rest:"60 sec"},
      {name:"Push-Up",              sets:4, reps:"8–15",    rest:"60 sec"},
      {name:"Bent Over Row",        sets:4, reps:"10–15",   rest:"60 sec"},
      {name:"Shoulder Press",       sets:3, reps:"10–15",   rest:"60 sec"},
      {name:"Walking Lunge",        sets:3, reps:"12/leg",  rest:"60 sec"},
      {name:"Romanian Deadlift",    sets:3, reps:"10–15",   rest:"60 sec"},
      {name:"Pull-Up / Lat Pulldown",sets:3,reps:"8–12",    rest:"60 sec"},
      {name:"Kettlebell Swing",     sets:3, reps:"15–20",   rest:"45 sec"},
      {name:"Plank to Push-Up",     sets:3, reps:"8–12",    rest:"45 sec"},
    ],
    core:[
      {name:"Plank",            sets:3, reps:"45–60 sec"},
      {name:"Russian Twist",    sets:3, reps:"20/side"},
      {name:"Mountain Climbers",sets:3, reps:"30–45 sec"},
    ],
    cardio:"HIIT Treadmill 15–20 min | Assault Bike 15–20 min | Rowing Machine 15–20 min",
    tempo:"2-1-2-0",
  },
  26: {
    day:26, focus:"BACK & BICEPS STRENGTH",
    warmup:["5 min treadmill walk","Arm circles x 15 fwd / x 15 back","Band pull-aparts x 15","Cat-Cow x 10","Scapular retractions x 15"],
    exercises:[
      {name:"Pull-Ups (or Assisted)", sets:4, reps:"6–10",      rest:"90 sec"},
      {name:"Lat Pulldown (Wide Grip)",sets:4, reps:"8–12",     rest:"75 sec"},
      {name:"Seated Cable Row",        sets:4, reps:"8–12",     rest:"75 sec"},
      {name:"Single Arm Dumbbell Row", sets:3, reps:"10–12/ea", rest:"75 sec"},
      {name:"Chest Supported Row",     sets:3, reps:"10–12",    rest:"60 sec"},
      {name:"Straight Arm Pulldown",   sets:3, reps:"12–15",    rest:"60 sec"},
      {name:"Barbell Curl",            sets:3, reps:"8–12",     rest:"60 sec"},
      {name:"Hammer Curl",             sets:3, reps:"10–12",    rest:"60 sec"},
      {name:"Concentration Curl",      sets:3, reps:"10–12/each",rest:"45 sec"},
    ],
    core:[
      {name:"Plank",              sets:3, reps:"45–60 sec"},
      {name:"Side Plank/Side",    sets:3, reps:"30–45 sec"},
      {name:"Cable Woodchop/Side",sets:3, reps:"12–15"},
    ],
    cardio:"HIIT Treadmill 15–20 min | Assault Bike 15–20 min | Rowing Machine 15–20 min",
    tempo:"2-1-2-0",
  },
  27: {
    day:27, focus:"SHOULDERS & TRAPS STRENGTH",
    warmup:["5 min treadmill walk","Arm circles x 15 fwd / x 15 back","Shoulder rolls x 15 each direction","Band pull-aparts x 15","Cat-Cow x 10","Scapular retractions x 15"],
    exercises:[
      {name:"Overhead Press",    sets:4, reps:"6–10",  rest:"90 sec"},
      {name:"Lateral Raise",     sets:4, reps:"8–12",  rest:"60 sec"},
      {name:"Arnold Press",      sets:3, reps:"8–12",  rest:"75 sec"},
      {name:"Upright Row",       sets:3, reps:"8–12",  rest:"60 sec"},
      {name:"Rear Delt Fly",     sets:3, reps:"12–15", rest:"60 sec"},
      {name:"Face Pull",         sets:3, reps:"12–15", rest:"60 sec"},
      {name:"Shrugs",            sets:4, reps:"10–15", rest:"60 sec"},
      {name:"Front Raise",       sets:3, reps:"10–12", rest:"45 sec"},
      {name:"Farmer's Carry",    sets:3, reps:"30–40 m",rest:"60 sec"},
    ],
    core:[
      {name:"Hanging Knee Raises",sets:3, reps:"12–15"},
      {name:"Russian Twist",      sets:3, reps:"20/side"},
      {name:"Plank Hold",         sets:3, reps:"45–60 sec"},
    ],
    cardio:"HIIT Treadmill 15–20 min | Assault Bike 15–20 min | Rowing Machine 15–20 min",
    tempo:"2-1-2-0",
  },
  28: {
    day:28, focus:"PEAK PERFORMANCE DAY — COMPLETE 4 ROUNDS",
    warmup:["5 min treadmill walk","Arm circles x 15 fwd / x 15 back","Leg swings x 15 each leg","Hip circles x 15 each direction","Bodyweight squats x 15"],
    exercises:[
      {name:"Push-Up",               sets:4, reps:"15–20",  rest:"45 sec"},
      {name:"Pull-Up / Lat Pulldown", sets:4, reps:"8–12",   rest:"45 sec"},
      {name:"Squat",                  sets:4, reps:"20",     rest:"45 sec"},
      {name:"Dumbbell Shoulder Press",sets:4, reps:"12–15",  rest:"45 sec"},
      {name:"Bent Over Row",          sets:4, reps:"12–15",  rest:"45 sec"},
      {name:"Walking Lunge",          sets:4, reps:"16/leg", rest:"45 sec"},
      {name:"Plank",                  sets:4, reps:"45–60 sec",rest:"30 sec"},
      {name:"Burpees",                sets:4, reps:"10–15",  rest:"60 sec"},
    ],
    core:[
      {name:"Kettlebell Swings", reps:"10"},
      {name:"Push Press",        reps:"10"},
      {name:"Box Jumps",         reps:"10"},
      {name:"Mountain Climbers", reps:"10/side"},
      {name:"Renegade Rows",     reps:"10/side"},
    ],
    cardio:"AMRAP 10 minutes — then 20 min HIIT Cardio of your choice",
    tempo:"2-1-2-0",
    note:"FINISH STRONG. BE PROUD. YOU DID THE WORK.",
  },
};
